/*
  Auto-extracted from pair.js switch-case during cmd/ refactor.
  Exposes: download_video
*/

module.exports = {
  name: 'download_video',
  aliases: [],
  execute: async (ctx) => {
    const { socket, msg, sender, args, quoted, text, reply, axios, ytmp4 } = ctx;
    try {
        const youtubeUrl = args[0];
        if (!youtubeUrl) return reply("❌ වලංගු YouTube Link එකක් ලැබී නැත.");

        try { await socket.sendMessage(sender, { react: { text: '🎥', key: msg.key } }); } catch (_) {}
        reply("📥 _*👑𝗞ᴀᴅɪ𝗬𝗮-𝙓-𝙈𝘿🔥*_ Extracting High-Quality MP4 Video..._");

        // මෙහිදී ඔබගේ YT Video Downloader API එක භාවිතා කරන්න (උදාහරණයක් ලෙස පහත පරිදි)
        const API_TOKEN = "aWK0z4";
        const YT_VIDEO_API = `https://whiteshadow-x-api.onrender.com/api/download/ytmp4`; // වීඩියෝ API එක

        const dlRes = await axios.get(`${YT_VIDEO_API}?url=${encodeURIComponent(youtubeUrl)}&quality=720&apitoken=${API_TOKEN}`);
        
        if (dlRes.data && dlRes.data.success && dlRes.data.result) {
            const videoDownloadUrl = dlRes.data.result.download_url;
            const songTitle = dlRes.data.result.title || "Kadiya-MD Video";

            // Send Video File
            await socket.sendMessage(sender, {
                video: { url: videoDownloadUrl },
                mimetype: 'video/mp4',
                caption: `📌 *Title:* ${songTitle}\n\n*Generated by Kadiya-X-MD*`
            }, { quoted: msg });

            try { await socket.sendMessage(sender, { react: { text: '✅', key: msg.key } }); } catch (_) {}
        } else {
            reply("❌ *Error:* වීඩියෝ එක ලබා ගැනීමට නොහැකි විය.");
        }
    } catch (e) {
        reply("❌ *Download Error:* " + e.message);
    }
  }
};
